
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

welcome:
    path: /
    controller: App\Controller\SubscriptionController::index
    methods: GET|HEAD
