kind: Namespace
apiVersion: v1
metadata:
  name: prod
  labels:
    name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comics-api-deployment
  namespace: prod
  labels:
    app: comics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comics-api
  template:
    metadata:
      labels:
        app: comics-api
    spec:
      containers:
        - name: comics-api
          image: klaital/comics-web:142d3b2d7e9bf73cb4a43e6a52fe73777531ccd3
          ports:
            - name: http-comics-api
              containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: REALM
              value: 'prod'
            - name: HOSTNAME
              value: 'comics.klaital.com'
            - name: PORT
              value: '31698'
            - name: DB_HOST
              value: 'mysql.abandonedfactory.net'
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: comics-api-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: comics-api-secret
                  key: db-password
            - name: DB_NAME
              value: 'webcomics'
            - name: DB_PORT
              value: '3306'
            - name: LOG_LEVEL
              value: 'debug'
            - name: LOG_PRETTY
              value: 'false'
          readinessProbe:
            httpGet:
              path: /healthz?readiness
              port: 8080
            periodSeconds: 20
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /healthz?liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: comics-api-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: comics-api
  ports:
    - name: http-comics-api
      port: 80
      targetPort: 8080
      protocol: TCP
